services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production #TODO fix an env file
      - DB_PATH=/app/database/transcendence.db
    ports:
      - 3000:3000
    volumes:
      - database:/app/database
      - ./backend/assets:/app/assets
    restart: always
    networks:
      - transcendence

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app #for hot reload, syncs local code to container
      - /app/node_modules #for hot reload, anonymos volume to avoid node_modules conflicts from container and host
    environment:
      - CHOKIDAR_USEPOLLING=true  # file watching
      - SERVER_HOSTNAME=${SERVER_HOSTNAME}
      - GAME_SERVER_PORT=${GAME_SERVER_PORT}
    depends_on:
      - backend
    restart: always
    networks:
      - transcendence

volumes:
  database:
    name: transcendence_database
    driver: local
    
networks:
  transcendence:
    driver: bridge
  
# to add in service: env file 