services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/database/transcendence.db
    expose:
      - 3000
    volumes:
      - database:/app/database
      - uploads:/app/uploads  
    restart: always
    networks:
      - transcendence
    develop:
      watch:
        - action: rebuild
          path: ./backend/src
          target: /app/src

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.real
    ports:
      - 8080:8080
    depends_on:
      - backend
    restart: always
    networks:
      - transcendence

  gameserver:
    container_name: gameserver
    build:
      context: ./server-side-pong
      dockerfile: Dockerfile.dev
    expose:
      - 8081
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    networks:
      - transcendence

volumes:
  database:
    name: transcendence_database
    driver: local
  uploads:            
    name: transcendence_uploads
    driver: local
networks:
  transcendence:
    driver: bridge