services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production #TODO fix an env file
      - DB_PATH=/app/database/transcendence.db
    ports:
      - 3000:3000
    volumes:
      - database:/app/database
      - uploads:/app/uploads  
    restart: always
    networks:
      - transcendence
    develop:
      watch:
        - action: rebuild
          path: ./backend/src
          target: /app/src

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.real
    ports:
      - 8080:8080
    depends_on:
      - backend
    restart: always
    networks:
      - transcendence

  gameserver:
    container_name: gameserver
    build:
      context: ./server-side-pong
      dockerfile: Dockerfile.dev
    ports:
      - 8081:8081
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    networks:
      - transcendence

volumes:
  database:
    name: transcendence_database
    driver: local
  uploads:            
    name: transcendence_uploads
    driver: local
networks:
  transcendence:
    driver: bridge
  
# to add in service: env file 